services:
  sciencebeam:
    container_name: sciencebeam
    image: elifesciences/sciencebeam-parser
    ports:
      - "8070:8070"
  rtransparent:
    container_name: rtransparent
    image: nimhdsst/rtransparent:staging
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "curl", "--include", "--request", "GET", "http://localhost:8071/health"]
      interval: 1s
      timeout: 3s
      retries: 3
