name: local-osm
services:
  rtransparent:
    build:
      context: .
      dockerfile: ./external_components/rtransparent/Dockerfile
    volumes:
      - ./external_components/rtransparent:/app

  web_api:
    container_name: web_api
    environment:
      - MONGODB_URI=mongodb://db:27017/osm
    build:
      context: .
      dockerfile: ./web/api/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./web/api:/app/app
      - ./osm:/opt/osm/osm
    working_dir: /app/app
    command: ["fastapi","dev","--host","0.0.0.0","--port","80"]
    depends_on:
        - db

  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: ./web/dashboard/Dockerfile
    environment:
      - MONGODB_URI=mongodb://db:27017/osm
    working_dir: /app
    ports:
      - "8501:8501"
    volumes:
      - ./web/dashboard:/app
      - ./osm:/opt/osm/osm

  db:
    container_name: db
  # use old version of mongo to avoid Apple Instruction set error
    image: mongo:4.4.6
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=osm
