name: local-osm
services:

  rtransparent:
    container_name: rtransparent
    build:
      context: .
      dockerfile: ./external_components/rtransparent/Dockerfile
    volumes:
      - ./external_components/rtransparent:/app

  llm_extraction:
    container_name: llm_extraction
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-NOKEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-NOKEY}
    build:
      context: .
      dockerfile: ./external_components/llm_extraction/Dockerfile
    volumes:
      - ./external_components/llm_extraction:/app
    depends_on:
      - base
    develop:
      watch:
        - action: sync+restart
          path: ./osm
          target: /opt/osm/osm
          ignore:
            - __pycache__

############ Development images ############

  db:
  # use old version of mongo to avoid Apple Instruction set error
    image: mongo:4.4.6
    container_name: db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=osm

  base:
    command: ["echo", "base image"]
    image: nimhdsst/osm_base:latest
    build:
      context: .
      dockerfile: Dockerfile.base

  dashboard:
    container_name: dashboard
    environment:
      - MONGODB_URI=mongodb://db:27017/osm
    image: nimhdsst/osm_dashboard:latest
    build:
      context: .
      dockerfile: ./web/dashboard/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./web/dashboard:/app
      - ./dashboard_data:/opt/data
    depends_on:
      - db
      - base
    develop:
      watch:
        - action: sync+restart
          path: ./osm
          target: /opt/osm/osm
          ignore:
            - __pycache__

  web_api:
    container_name: web_api
    working_dir: /app/app
    command: ["fastapi","dev","--host","0.0.0.0","--port","80"]
    environment:
      - MONGODB_URI=mongodb://db:27017/osm
    image: nimhdsst/osm_web_api:latest
    build:
      context: .
      dockerfile: ./web/api/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./web/api:/app/app
    depends_on:
      - db
      - base
    develop:
      watch:
        - action: sync+restart
          path: ./osm
          target: /opt/osm/osm
          ignore:
            - __pycache__
