name: osm
channels:
  - conda-forge
  - nodefaults
dependencies:
  - fastapi
  - lxml
  - pandas
  - pip
  - psutil
  - python
  - requests
  - rpy2
  - uvicorn
  # Dependencies for rtransparent
  - r-crul
  - r-devtools
  - r-dplyr
  - r-furrr
  - r-future
  - r-globals
  - r-hoardr
  - r-httpcode
  - r-lazyeval
  - r-lubridate
  - r-magrittr
  - r-pbapply
  - r-pdftools
  - r-plyr
  - r-purrr
  - r-qpdf
  - r-readr
  # - r-rentrez
  - r-rlang
  - r-stringr
  - r-tibble
  - r-tidyr
  - r-tidyselect
  - r-timechange
  - r-tokenizers
  - r-triebeard
  - r-urltools
  - r-utf8
  # - r-XML
  - r-xml2
  - pip:
    - metapub
