name: osm
channels:
  - conda-forge
  - nodefaults
dependencies:
  - fastapi
  - lxml
  - pandas
  - pip
  - python
  - requests
  - uvicorn
  - llama-index
  - llama-index-llms-openai
  - pip:
    - odmantic
    - llama-index-program-openai
