services:
  osm_web_api:
    image: osm_web_api
    environment:
      - MONGODB_URI="mongodb+srv://the_rest_of_the_connection_string"
    build:
      context: ..
      dockerfile: ./web_api/Dockerfile
    ports:
      - 80:80
  traefik:
    image: traefik:v3.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik"
      - "./letsencrypt:/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
