services:
  osm_web_api:
    image: osm_web_api
    environment:
      - MONGODB_URI="mongodb+srv://johnlee:<password>@cluster0.6xo8ws7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    build:
      context: ../..
      dockerfile: ./docker_images/web_api/Dockerfile
    ports:
      - 80:80
  traefik:
    image: traefik:v3.1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/etc/traefik"
      - "./letsencrypt:/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
