name: osm
services:
    js_dashboard_backend:
        image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/api-shared:${RELEASE_TAG}"
        pull_policy: always
        restart: always
        expose:
            - "8000"
        networks:
            - traefik-public
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
                delay: 10s

    js_dashboard:
        image: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/js_dashboard-shared:${RELEASE_TAG}"
        pull_policy: always
        restart: always
        environment:
            - VITE_API_BASE_URL=http://js_dashboard_backend:8000/api
        labels:
            - traefik.enable=true
            - traefik.docker.network=osm_traefik-public
            - traefik.http.routers.js_dashboard.rule=Host(`${DEPLOYMENT_URI}`)
            - traefik.http.routers.js_dashboard.entrypoints=web,websecure
            - traefik.http.services.js_dashboard.loadbalancer.server.port=5173
            - traefik.http.routers.js_dashboard.tls=true
            - traefik.http.routers.js_dashboard.tls.certresolver=le
        expose:
            - "5173"
        networks:
            - traefik-public
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
                delay: 10s

    reverse_proxy:
        image: traefik
        restart: always
        command:
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --entryPoints.web.http.redirections.entryPoint.to=websecure
            - "--certificatesresolvers.le.acme.email=${LETSENCRYPT_ADMIN_EMAIL}"
            - --certificatesresolvers.le.acme.storage=/certificates/acme.json
            - --certificatesresolvers.le.acme.tlschallenge=true
            - --log
            - --accesslog
            - --log.level=DEBUG
        ports:
            - 80:80
            - 8080:8080
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - traefik-public-certificates:/certificates
        networks:
            - traefik-public

volumes:
    traefik-public-certificates:

networks:
    traefik-public:
