name: Deploy to Docker image to AWS ECR

on:
  workflow_dispatch:
  push:
    # tags:
    #   - 'v*.*.*' # Matches version tags like v1.0.0

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        deployment: ["api", "dashboard"]
    uses: ./.github/workflows/build-docker.yml
    with:
      deployment: ${{ matrix.deployment }}

  docker-up:
    needs: [build]
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}
    name: Deploy and run docker images on EC2
    uses: ./.github/workflows/docker-up.yml
    secrets: inherit
    with:
      parent_trigger: ${{ github.event_name }}
      
