name: Deploy to Docker image to AWS ECR

on:
  workflow_dispatch:
  push:
    # tags:
    #   - 'v*.*.*' # Matches version tags like v1.0.0

permissions:
  id-token: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        deployment: ["api", "dashboard"]
    uses: ./.github/workflows/build-docker.yml
    with:
      deployment: ${{ matrix.deployment }}

  docker-up:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && !cancelled() && needs.build.result == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      - name: Set stage environment
        run: |
          export ENVIRONMENT=stage
        if: ${{ github.event_name == 'push' }}
        
      - name: Set prod environment
        run: |
          export ENVIRONMENT=prod
        if: ${{ github.event_name == 'workflow_dispatch' }}
          
      - name: Deploy and run docker images on EC2
        uses: ./.github/workflows/docker-up.yml
        with:
          environment: ${{ env.ENVIRONMENT }}
      
