name: Push to Docker image to AWS ECR and deploy to AWS EC2

on:
  workflow_dispatch:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    strategy:
      matrix:
        deployment: ["api", "dashboard"]
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    with:
      deployment: ${{ matrix.deployment }}

  docker-up:
    needs: [build-and-push]
    if: ${{ always() && !cancelled() && needs.build-and-push.result == 'success' }}
    name: Deploy and run docker images on EC2
    uses: ./.github/workflows/docker-up.yml
    secrets: inherit
    with:
      parent_trigger: ${{ github.event_name }}
      
